# Generated by Django 5.1.7 on 2025-04-11 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0006_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
