# Generated by Django 5.1.7 on 2025-04-17 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0008_patientprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppointmentConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_daily_appointments', models.PositiveIntegerField(default=30)),
                ('max_per_hour', models.PositiveIntegerField(default=3)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Appointment Configuration',
                'verbose_name_plural': 'Appointment Configurations',
            },
        ),
        migrations.AddField(
            model_name='appointment',
            name='sex',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], default='O', max_length=1),
        ),
        migrations.AddField(
            model_name='appointment',
            name='time',
            field=models.TimeField(default='09:00:00'),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='sex',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], default='O', max_length=1),
        ),
    ]
